### ISSUE TITLE
usage clarification

### ISSUE THREAD

**Issue by dcsan** [JasonBoy/wechat-jssdk#10]
hi! I'm trying to check how to use the oAuth part

what we really want is to get the user's openID when they are accessing an H5 page linked from within an official account (from a menu item actually)

looking at the oAuth callback
https://github.com/JasonBoy/wechat-jssdk#oauth

```js
//default callback url
router.get('/wechat/oauth-callback', function (req, res) {
  wx.oauth.getUserInfo(req.query.code)
          .then(function(userProfile) {
            console.log(userProfile)
            res.render("demo", {
              wechatInfo: userProfile
            });
          });
});
```

so this is server side code obviously. what is `wx` in this case?

```js
const wx = new WeChat(wechatInfo);
```

Am i right to understand, 
you've created an npm wechat JS-SDK, which is *different* from the official tencent js-sdk
and you're suggesting to initialize it with `wx` ?
this is a bit confusing, as the client side official tencent SDK is also referred to as `wx` in their examples.

**Comment by JasonBoy** [comment]
the `wx` here at `const wx = new WeChat(wechatInfo);`  has nothing to do with the tencent browser side wx object, here it's just a instance name of WeChat class, which is used to do the server side task, like getting the  token, jsapi_ticket, manage token/ticket data..., you can use anything you want, e.g:
`const myWechatInstance = new WeChat(wechatInfo);`,

**Comment by dcsan** [comment]
tx for the quick response. 
so the `req.query.code` above 
is the code returned from the redirect / silent login?

https://mp.weixin.qq.com/wiki?t=resource/res_main&id=mp1421140842

I'm really just trying to get an openID, not the rest of the profile info. 
Is the oAuth endpoint the only way to get that?

separate from that opening an oAuth signin from within a wechat official account (so we already have their permission and info) - will that skip the signin button popup for existing followers?

**Comment by JasonBoy** [comment]
checkout the implicit/slient oauth  in the demo(`demo/index.js`), which does not need user's permission.
in `/` route to gen the implicit oauth url, and
in  `/implicit-oauth` route(redirected here by wechat) to get the user base info with the code retrieved from the implicit oauth url redirect above

**Comment by JasonBoy** [comment]
Fire a new issue if you still have confusions👀
