### ISSUE TITLE
调用语法糖callWechatApi时报错，急急急

### ISSUE THREAD

**Issue by bibiehy** [JasonBoy/wechat-jssdk#19]
版本："wechat-jssdk": "^3.0.11"

const weConfig = {
    ......
   jsApiList:['onMenuShareTimeline', 'onMenuShareAppMessage',  'onMenuShareQZone'],
   success:function(wechatObj ){ console.log('签名成功');},
   ......
}
const wechatObj  = new WechatJSSDK(weConfig);

开启debug
签名成功的回调能执行到
当调用  **wechatObj.callWechatApi('onMenuShareTimeline', apiConfig);** 
![image](https://user-images.githubusercontent.com/35096473/36889372-a1c07442-1e34-11e8-9314-717cee8667b6.png)

这是什么情况

**Comment by JasonBoy** [comment]
是在success回调里调的么，还是在外面，外面应该是会报错的

**Comment by bibiehy** [comment]
@JasonBoy 试了一下，必须放在 success 里面去调用才可以

**Comment by JasonBoy** [comment]
是的，微信验证是异步的，所以只能在回调里用，你可以通过promise或者async封装一下
