### ISSUE TITLE
How to use verifySignature

### ISSUE THREAD

**Issue by IpShot** [JasonBoy/wechat-jssdk#2]
Hi. 
Don't understand when and where I should to use verify from paragraph 1 here (https://github.com/JasonBoy/wechat-jssdk#setup-your-wechat-env).
Should it be configured somewhere in wechat account (because you wrote "let wechat to verify" or I should call it myself somewhere? 
Thanks.

**Comment by JasonBoy** [comment]
@IpShot yes, you may need to login to the wechat dashboard, and when you configure the server information, wechat will call this api to verify that you have the right to access your own server.
In dashboard: 
开发 -> 基本配置 -> 服务器配置（修改配置）,   
when you click save, it will send the api to your server, you should deploy your server before saving

**Comment by JasonBoy** [comment]
@IpShot any update?

**Comment by IpShot** [comment]
@JasonBoy not yet, waiting to deploy to production to check how it's working. Looks like trait of wechat, he doesn't want to work with url different from main verified domain.

**Comment by JasonBoy** [comment]
@IpShot hey man,  how about now? otherwise I will close this...

**Comment by IpShot** [comment]
@JasonBoy Hi. Sorry for delay. Yes, close it. If something will not work I just open new one, thanks :)
