### ISSUE TITLE
H5页面用微信登录必须要扫二维码吗？

### ISSUE THREAD

**Issue by zwl1619** [JasonBoy/wechat-jssdk#21]
H5页面用微信登录必须要扫二维码吗？

**Comment by JasonBoy** [comment]
微信里面打开不需要

**Comment by zwl1619** [comment]
比如我用手机chrome打开百度搜索->输入某个关键词->得到搜索列表->点击其中一项->进入该网站（H5），这时仍然是chrome浏览器打开的该页面，那么，这时怎么调用微信来打开该网站呢？

**Comment by JasonBoy** [comment]
应该没有这样自动的方法, jssdk也是适用于微信APP内

**Comment by zwl1619** [comment]
假如现在已经在微信浏览器里面打开了该页面，用 jssdk的那个api来授权登录？
https://mp.weixin.qq.com/wiki?t=resource/res_main&id=mp1421141115

**Comment by JasonBoy** [comment]
请参考[demo](https://github.com/JasonBoy/wechat-jssdk/wiki/%E4%B8%AD%E6%96%87%E4%BD%BF%E7%94%A8%E6%96%87%E6%A1%A3#demo)， 里面有详细的例子
