### ISSUE TITLE
can't use jssdk in react 

### ISSUE THREAD

**Issue by songxh2** [JasonBoy/wechat-jssdk#22]
用import时，提示define 错误，去掉后提示如下：
import WechatJSSDK from '../components/weichat-jssdk/client'
"export 'default' (imported as 'WechatJSSDK') was not found in 'weichat-jssdk/client'

采用//const WechatJSSDK = require( '/weichat-jssdk/client')用的时候浏览器出错

**Comment by JasonBoy** [comment]
`require('wechat-jssdk/dist/client')`中间有个dist

**Comment by songxh2** [comment]
我已经将client目录下的文件拷贝到我自己的项目目录里了，react+dva 老版本运行时没问题，但升级dva后老提示"export 'default' (imported as 'WechatJSSDK') was not found in 'weichat-jssdk/client'。并且运行到这个点时出错！

**Comment by JasonBoy** [comment]
试一下`./libs/client.js` 原始文件

**Comment by songxh2** [comment]
试了下./libs/client.js 原始文件，但还是报错！
后来我将
module.exports = WechatJSSDK;
换成：
export default WechatJSSDK;
就好了。谢谢！

**Comment by JasonBoy** [comment]
我之前在react的项目里直接用打包后的client也是可以的，而且是以UMD 打包，不知道你的项目可能配了只支持ES Module方式

**Comment by songxh2** [comment]
@JasonBoy 很可能只支持ES Module方式，但没仔细看了，能通过就行。。
