### ISSUE TITLE
浏览器端能不能有个ready方法等待核心库的加载？很苦恼～

### ISSUE THREAD

**Issue by 79229788** [JasonBoy/wechat-jssdk#24]
刚new完WechatJSSDK，并不能马上获取到window.wx，那么自然而然使用里面的callWechatApi方法通通报错！！，看了源码才发现new的过程中还有一个loadScript方法在异步加载核心库，这下蛋疼了，没有对外提供一个ready方法让我们等待这个异步，那么何时使用wx的方法，很苦恼，计时器都不那么好用，希望能提供一个该接口（考虑做个事件触发器单独触发一个ready，或者构造器里面直接弄个回调也可以简单粗暴好用）。谢谢

**Comment by JasonBoy** [comment]
new的时候options里面可以传success，error回调，请查看一下readme浏览器端的使用

**Comment by 79229788** [comment]
好吧，没注意到配置里还有回调，直接当官方的配置来写了，忘了这个是你拓展的了，不好意思哈
