### ISSUE TITLE
你好，希望可以自定义scope,这样的话， 非公众号appid也可以使用这个package了

### ISSUE THREAD

**Issue by Nomia** [JasonBoy/wechat-jssdk#3]
你好，@JasonBoy，希望可以自定义scope，这样的话， 非公众号appid也可以使用这个package了

我看了package中的lib/oauth.js文件，里面有一些默认的配置，默认配置的scope是snsapi_userinfo，这个scope公众号(mp.weixin.qq.com)里面生成的appid可以使用，但是通过open.weixin.qq.com生成的开发者appid是无法使用的，open.weixin.qq.com里面生成的app只能使用snsapi_login scope，

但是在wechat-jssdk的package中并没有自定义scope的地方，希望可以配置一下，谢谢，这个sdk非常棒!

(也可能是我没有找到。如果是我没有找到，希望可以帮助下我，thx)

**Comment by JasonBoy** [comment]
@Nomia thanks for try it, 
I will take a look, and will add this config asap if necessary. I didn't consider the conditions on open.weixin.qq.com 😭

**Comment by Nomia** [comment]
thx for the quick reply :> @JasonBoy

**Comment by JasonBoy** [comment]
@Nomia use `wx.oauth.generateOauthUrlByScope(myRedirectUrl, scope)`, use 2rd `scope` param to pass your own "snsapi_login", use returned oauth url instead of the default `wx.oauth.snsUserInfoUrl`, 
pls take a look for the change to see if it meets your needs

**Comment by JasonBoy** [comment]
your are using 2.x, right?

**Comment by Nomia** [comment]
yep,  "2.1.0"

**Comment by Nomia** [comment]
thx, I'll give it a try :>

**Comment by Nomia** [comment]
I think it'll work just fine. I'm waiting for the npm package update :P

**Comment by JasonBoy** [comment]
@Nomia Merged, try v2.2.0 now

**Comment by Nomia** [comment]
Great, never thought so fast, thx~

**Comment by JasonBoy** [comment]
Can I close this now? or you are still debugging?
