### ISSUE TITLE
请教二级目录

### ISSUE THREAD

**Issue by yangchengwork** [JasonBoy/wechat-jssdk#5]
@JasonBoy 您好！现在使用nginx反向代码，如果直接使用www.gumpyang.com.cn就可以显示signature OK，但如果设置二级代码如www.gumpyang.com.cn/wxjs，打开时就会如下错误
GET http://www.gumpyang.com.cn/get-signature?url=http%3A%2F%2Fwww.gumpyang.com.cn%2Fwxjs%2F 404 (Not Found)

请教如何可以定位是我哪里设置错误了

**Comment by yangchengwork** [comment]
是我自己没有注意，在demo下需要同时修改index.html中56行的url，但现在会出现config:invalid url domain

**Comment by JasonBoy** [comment]
`/get-signature`是你自己的路由，你要自己加到你的路由中吧，url是任意都无所谓，没有二级的限制的

**Comment by yangchengwork** [comment]
找到问题了，忘记修改wechatRedirectUrl了，很在多谢您了

**Comment by JasonBoy** [comment]
wechatRedirectUrl是做OAuth的，跟那个jssdk貌似没有关系吧 ❓

**Comment by yangchengwork** [comment]
在dispatching GET /get-signature?url=时估计会用到oauth，此时估计在读wechatRedirectUrl了，我之前没有修改这个就出问题了。你这个项目真是太好了。多谢

**Comment by JasonBoy** [comment]
@yangchengwork 🆒

**Comment by yangchengwork** [comment]
@JasonBoy 现在点OAuth和OAuth without new code时返回key是undefined，咱们是新启动一个问题，还是在这里请教您

**Comment by JasonBoy** [comment]
新开一个吧
