### ISSUE TITLE
vue无法使用fs

### ISSUE THREAD

**Issue by samjoeyang** [JasonBoy/wechat-jssdk#52]
hi，配置中有paymentCertificatePfx: fs.readFileSync(path.join(process.cwd(), 'cert/apiclient_cert.p12'))，而在vue-cli中无法引入fs，请问有什么解决方案？

**Comment by JasonBoy** [comment]
这个是node 服务端的代码，不是浏览器端的代码， 肯定没有fs

**Comment by samjoeyang** [comment]
晕，所有的配置信息都在一起，因为这个问题一直编译不通过。
现在把读取文件这行注释掉了，终于运行了
