### ISSUE TITLE
请教OAuth如何使用

### ISSUE THREAD

**Issue by yangchengwork** [JasonBoy/wechat-jssdk#6]
@JasonBoy 请教一下，现在部署OK后，点击OAuth和OAuth without new code都会显示
  wechat Error: please get new code!
  wechat     at /home/gump/work/gump/github/wechat-jssdk/lib/OAuth.js:164:23
  wechat     at process._tickCallback (node.js:368:9) +0ms
查看key都是undefined，打印req.session后，信息如下
{"cookie":{"originalMaxAge":null,"expires":null,"httpOnly":true,"path":"/"}}
其中没有openid，请教是配置的问题吗？
同时请教demo下的oauth.html是点击OAuth后跳转吗？

**Comment by JasonBoy** [comment]
如果你直接点without new code， 打出来就是undefined，但是结果是对的应该，还是会让你去授权，打出的错误仅仅是debug用而已，对逻辑没有影响，without只是会去判断一下，没有的话走Oauth那个连接

**Comment by JasonBoy** [comment]
你第二次再点without连接，就不会是undefined，也不会有报错，第一次本来session什么都没有，那是正常

**Comment by yangchengwork** [comment]
现在没有进入到让我授权，会出现“该链接无法访问”

**Comment by JasonBoy** [comment]
你微信里的oauth域名配了么

**Comment by yangchengwork** [comment]
是我之前没有配置，现在配置后http://www.gumpyang.com.cn/wxjs/或http://www.gumpyang.com.cn/wxjs/oauth一直显示
redirect_uri 参数错误

**Comment by JasonBoy** [comment]
你微信那里配了么，网页授权地址

**Comment by yangchengwork** [comment]
是指“网页帐号	网页授权获取用户基本信息”这里吗？

**Comment by JasonBoy** [comment]
应该是，[文档是这个](https://mp.weixin.qq.com/wiki/4/9ac2e7b1f1d22e9e57260f6553822520.html)，回调域名的配置

**Comment by yangchengwork** [comment]
这个坑很大，短时间搞不定。要多试试了

**Comment by JasonBoy** [comment]
主要就是你配置的`wechatRedirectUrl`域名要与微信那边配的网页授权回调地址一直，不然会包redirect_uri错误

**Comment by yangchengwork** [comment]
请教网页授权这边有"http://"吗？看文档说不要

**Comment by JasonBoy** [comment]
不用
<img width="719" alt="screen shot 2017-02-17 at 6 28 33 pm" src="https://cloud.githubusercontent.com/assets/2911620/23061999/f95da3d4-f53e-11e6-9022-29ea33adb126.png">

**Comment by yangchengwork** [comment]
谢谢，用IP地址就可以，真是有些纠结了。今天多谢您了。

**Comment by JasonBoy** [comment]
不谢，但是你先上只能用域名

**Comment by yangchengwork** [comment]
补充一下，微信这边只能用域名。我之前用了二级域名，所以一直有问题。
