### ISSUE TITLE
支付请求95%的几率出现Z_DATA_ERROR：unknown compression method

### ISSUE THREAD

**Issue by 79229788** [JasonBoy/wechat-jssdk#64]
如题，之前都是好好的，不知道为何从7月6号开始出现这种错误，而且不是100%出现，是小几率正常
{ ReadError: unknown compression method
    at EventEmitter.emitter.on (/var/www/XXXX/deploy/node_modules/_got@9.6.0@got/source/as-promise.js:28:12)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  name: 'ReadError',
  code: 'Z_DATA_ERROR',
  host: 'api.mch.weixin.qq.com',
  hostname: 'api.mch.weixin.qq.com',
  method: 'POST',
  path: '/pay/unifiedorder',
 ....

不支持的压缩方法？？？没找到是哪里的原因，是微信支付请求处理改版了还是其他什么BUG？
我尝试把got换成了axios，就恢复正常了，希望关注下，目前在我们项目中got确实有问题

**Comment by JasonBoy** [comment]
是压根没发出去，还是response处理处理报错？

**Comment by 79229788** [comment]
我重新看了下，这个报错是没发出去吧，在catch中捕获，打印的完整error，主要奇怪就奇怪在不是100%请求出错，而是部分请求会正常，请求内容都一样，只是请求重试。当重试很多次后就有一次会成功（不过里面的支付params里的一些id会重新生成变化，如订单号，而其它主体内容每次重试都一致），所以不知道哪里坏了，Google了这种报错，几乎没人遇到，所以很棘手不知道哪里坏了，所以我只能把got换成了我更熟悉的axios，两者使用方法都差不多改动不大，我就换上了，然后就莫名其妙的彻底好了。下面是完整报错：
```
{ ReadError: unknown compression method
    at EventEmitter.emitter.on (/var/www/xxx/deploy/node_modules/_got@9.6.0@got/source/as-promise.js:28:12)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  name: 'ReadError',
  code: 'Z_DATA_ERROR',
  host: 'api.mch.weixin.qq.com',
  hostname: 'api.mch.weixin.qq.com',
  method: 'POST',
  path: '/pay/unifiedorder',
  socketPath: undefined,
  protocol: 'https:',
  url: 'https://api.mch.weixin.qq.com/pay/unifiedorder',
  gotOptions:
   { path: '/pay/unifiedorder',
     protocol: 'https:',
     slashes: true,
     auth: null,
     host: 'api.mch.weixin.qq.com',
     port: null,
     hostname: 'api.mch.weixin.qq.com',
     hash: null,
     search: null,
     query: null,
     pathname: '/pay/unifiedorder',
     href: 'https://api.mch.weixin.qq.com/pay/unifiedorder',
     retry:
      { retries: [Function],
        methods: [Set],
        statusCodes: [Set],
        errorCodes: [Set] },
     headers:
      { 'user-agent': 'got/9.6.0 (https://github.com/sindresorhus/got)',
        'accept-encoding': 'gzip, deflate',
        'content-length': 685 },
     hooks:
      { beforeRequest: [],
        beforeRedirect: [],
        beforeRetry: [],
        afterResponse: [],
        beforeError: [],
        init: [] },
     decompress: true,
     throwHttpErrors: true,
     followRedirect: true,
     stream: false,
     form: false,
     json: false,
     cache: false,
     useElectronNet: false,
     method: 'POST',
     body:
      '<xml>\n  <appid>xxx</appid>\n  <mch_id>xxx</mch_id>\n  <nonce_str>xxx</nonce_str>\n  <sign_type>MD5</sign_type>\n  <out_trade_no>xxxx</out_trade_no>\n  <notify_url>https://xxx</notify_url>\n  <trade_type>JSAPI</trade_type>\n  <device_info>WEB</device_info>\n  <body>xxx</body>\n  <product_id>xxx</product_id>\n  <detail>xx</detail>\n  <total_fee>xx</total_fee>\n  <time_start>xxx</time_start>\n  <spbill_create_ip>xxx</spbill_create_ip>\n  <openid>xxx</openid>\n  <sign>xxxx</sign>\n</xml>' } }
```

**Comment by zhaoyanxiang** [comment]
> 我重新看了下，这个报错是没发出去吧，在catch中捕获，打印的完整error，主要奇怪就奇怪在不是100%请求出错，而是部分请求会正常，请求内容都一样，只是请求重试。当重试很多次后就有一次会成功（不过里面的支付params里的一些id会重新生成变化，如订单号，而其它主体内容每次重试都一致），所以不知道哪里坏了，Google了这种报错，几乎没人遇到，所以很棘手不知道哪里坏了，所以我只能把got换成了我更熟悉的axios，两者使用方法都差不多改动不大，我就换上了，然后就莫名其妙的彻底好了（我也尝试过got的新版本，结果新版格式有报错，就没弄了）。下面是完整报错：
> 
> ```
> { ReadError: unknown compression method
>     at EventEmitter.emitter.on (/var/www/xxx/deploy/node_modules/_got@9.6.0@got/source/as-promise.js:28:12)
>     at process._tickCallback (internal/process/next_tick.js:68:7)
>   name: 'ReadError',
>   code: 'Z_DATA_ERROR',
>   host: 'api.mch.weixin.qq.com',
>   hostname: 'api.mch.weixin.qq.com',
>   method: 'POST',
>   path: '/pay/unifiedorder',
>   socketPath: undefined,
>   protocol: 'https:',
>   url: 'https://api.mch.weixin.qq.com/pay/unifiedorder',
>   gotOptions:
>    { path: '/pay/unifiedorder',
>      protocol: 'https:',
>      slashes: true,
>      auth: null,
>      host: 'api.mch.weixin.qq.com',
>      port: null,
>      hostname: 'api.mch.weixin.qq.com',
>      hash: null,
>      search: null,
>      query: null,
>      pathname: '/pay/unifiedorder',
>      href: 'https://api.mch.weixin.qq.com/pay/unifiedorder',
>      retry:
>       { retries: [Function],
>         methods: [Set],
>         statusCodes: [Set],
>         errorCodes: [Set] },
>      headers:
>       { 'user-agent': 'got/9.6.0 (https://github.com/sindresorhus/got)',
>         'accept-encoding': 'gzip, deflate',
>         'content-length': 685 },
>      hooks:
>       { beforeRequest: [],
>         beforeRedirect: [],
>         beforeRetry: [],
>         afterResponse: [],
>         beforeError: [],
>         init: [] },
>      decompress: true,
>      throwHttpErrors: true,
>      followRedirect: true,
>      stream: false,
>      form: false,
>      json: false,
>      cache: false,
>      useElectronNet: false,
>      method: 'POST',
>      body:
>       '<xml>\n  <appid>xxx</appid>\n  <mch_id>xxx</mch_id>\n  <nonce_str>xxx</nonce_str>\n  <sign_type>MD5</sign_type>\n  <out_trade_no>xxxx</out_trade_no>\n  <notify_url>https://xxx</notify_url>\n  <trade_type>JSAPI</trade_type>\n  <device_info>WEB</device_info>\n  <body>xxx</body>\n  <product_id>xxx</product_id>\n  <detail>xx</detail>\n  <total_fee>xx</total_fee>\n  <time_start>xxx</time_start>\n  <spbill_create_ip>xxx</spbill_create_ip>\n  <openid>xxx</openid>\n  <sign>xxxx</sign>\n</xml>' } }
> ```

我也遇到了，能提供下修改后的代码吗，多谢了

**Comment by 79229788** [comment]
那看来got真有问题了，我这边暂时改了libs/utils中的这个方法，还的等作者修复这个问题，或者真的考虑换掉got了
/**
 * Send the payment request to wechat server
 * @param {string|Object} url
 * @param {object} options custom request options
 * @return {Promise}
 */
utils.sendWechatPaymentRequest = (url, options) => {
  const myOptions = Object.assign(
    {},
    defaultOptions,
    {
      json: false,
      method: 'POST',
    },
    options
  );
  //***** axios版本
  myOptions.data = myOptions.body;
  if(!myOptions.headers) myOptions.headers = {};
  myOptions.headers['Content-Type'] = 'text/xml';
  return axios(url, myOptions)
    .then(response => {
      return Promise.resolve(response.data);
    })
    .catch(err => {
      debug(err);
      return Promise.reject(
        err.response && err.response.data ? err.response.data : err
      );
    });
  //***** got版本
  // return got(url, myOptions)
  //   .then(response => {
  //     return Promise.resolve(response.body);
  //   })
  //   .catch(err => {
  //     debug(err);
  //     return Promise.reject(
  //       err.response && err.response.body ? err.response.body : err
  //     );
  //   });
};

**Comment by 79229788** [comment]
那看来got真有问题了，我这边暂时改了libs/utils中的这个方法，还的等作者修复这个问题，或者真的考虑换掉got了
/**
 * Send the payment request to wechat server
 * @param {string|Object} url
 * @param {object} options custom request options
 * @return {Promise}
 */
utils.sendWechatPaymentRequest = (url, options) => {
  const myOptions = Object.assign(
    {},
    defaultOptions,
    {
      json: false,
      method: 'POST',
    },
    options
  );
  //***** axios版本
  myOptions.data = myOptions.body;
  if(!myOptions.headers) myOptions.headers = {};
  myOptions.headers['Content-Type'] = 'text/xml';
  return axios(url, myOptions)
    .then(response => {
      return Promise.resolve(response.data);
    })
    .catch(err => {
      debug(err);
      return Promise.reject(
        err.response && err.response.data ? err.response.data : err
      );
    });
  //***** got版本
  // return got(url, myOptions)
  //   .then(response => {
  //     return Promise.resolve(response.body);
  //   })
  //   .catch(err => {
  //     debug(err);
  //     return Promise.reject(
  //       err.response && err.response.body ? err.response.body : err
  //     );
  //   });
};

**Comment by JasonBoy** [comment]
https://github.com/sindresorhus/got/issues/388 可能跟decompress: true 有关，你改成false呢，然后自己处理Buffer

**Comment by JasonBoy** [comment]
微信用的什么压缩方法？ @79229788

**Comment by 79229788** [comment]
😂我也不清楚，没关注过这个点，以前都好好的，突然就不行了

**Comment by 79229788** [comment]
myOptions.decompress = false; 加了这个果然好了，也不用自己处理buffer，返回结果一致

**Comment by zhaoyanxiang** [comment]
谢谢大家，作者有空发个新版吧，客户这炸锅了，中午开始就不能扫码支付了，可怕~~

**Comment by 79229788** [comment]
decompress：false这个可能需要变成默认配置了😂

**Comment by JasonBoy** [comment]
他那个got库到11还是默认true，感觉默认还是要，不然可能其他就坏了。。

**Comment by 79229788** [comment]
或者改成初始化可配置的选项？然后交给我们自己控制？这个问题应该会陆陆续续更多出现，我以为我是特例，结果发现还有中招的，也是莫名其妙就中招了，相关代码一两年没动了😂，目前感觉也只是支付请求出这个错（只有这个是对xml处理把，其它请求貌似都是json，这个压缩对xml难到有问题？），其它请求暂时没有出现过类似问题

**Comment by JasonBoy** [comment]
感觉微信支付的API动了手脚，或者你们node版本是不是变更过？

**Comment by 79229788** [comment]
用了这么久的axios，发现它也没有开启压缩。做什么都是正常的，不过也一直没关注这个点，可能没有压缩的需求，感觉gzip这种东西主要做静态页面加速的，也就是服务端给客户端传输静态页面用的，而做接口交互，感觉用不上这东西额，而且感觉也没必要哈

**Comment by 79229788** [comment]
没有动过的，这个版本好久都没动了，也不敢轻易动

**Comment by 79229788** [comment]
我看微信支付api出了v3大版本一段时间了，彻底告别了xml，不知道是不是新老接口统一了一部分东西，包括压缩方法等等，导致这里出错了，不过也只能猜，压缩要开启的话应该是客户端和服务端得保持高度一致，这个问题短期来看可能真只能取消压缩才能解决

**Comment by JasonBoy** [comment]
api 链接文档在哪里

**Comment by 79229788** [comment]
新版v3：https://pay.weixin.qq.com/wiki/doc/apiv3/index.shtml

**Comment by goldcome** [comment]
同样问题 不能支付
