### ISSUE TITLE
使用Oauth时出现的问题

### ISSUE THREAD

**Issue by lorriexingfang** [JasonBoy/wechat-jssdk#9]
你好！

我按照readme配置了微信公众平台，并修改了index.js后，点击Oauth一直有问题。步骤是：

配置：
1. 将我的微信号在公众平台注册了一个测试账号，在接下来的页面中按说明做了配置。token服务器在公网上(配置成类似：http://1.2.3.4:12345)，验证通过。
<img width="1197" alt="config_wechat_server" src="https://user-images.githubusercontent.com/10093649/26955348-06f2f534-4c6b-11e7-8449-fe9f516f8d80.png">
2. 使用这个页面的token，appid，appsecrect配置到index.js上去.
3. "wechatRedirectUrl"没有修改（"http://127.0.0.1/oauth")
4. 启动后，使用微信web开发者工具访问127.0.0.1，各种验证的load是ok的:
<img width="494" alt="22" src="https://user-images.githubusercontent.com/10093649/26955484-db33c3be-4c6b-11e7-9c44-84e3bf3479fd.png">
5. 然后访问Oauth页面，却进入页面：
<img width="375" alt="3" src="https://user-images.githubusercontent.com/10093649/26955515-03ae0a66-4c6c-11e7-84d1-834fe4a77093.png">
在进入这个页面前，网页console有GET 一个url失败（ERR_BLOCKED_BY_CLIENT）的错误。

请问以上配置步骤是否有问题？有哪里做得不对吗？

非常感谢！

**Comment by JasonBoy** [comment]
网页授权回调地址设置了么？
https://github.com/JasonBoy/wechat-jssdk/wiki/%E4%B8%AD%E6%96%87%E4%BD%BF%E7%94%A8%E6%96%87%E6%A1%A3
拉倒最先面的图

**Comment by lorriexingfang** [comment]
我在公众平台配置自己的sandbox测试微信号时，在页面上没有看到这一页。只有：“JS接口安全域名”。

在正式账号那个页面我确实看到了这个配置项。

**Comment by lorriexingfang** [comment]
就是这个“接口测试账号”：

https://mp.weixin.qq.com/debug/cgi-bin/sandbox?t=sandbox/login

**Comment by JasonBoy** [comment]
一直往下拉到这个地方（网页授权。。。）点`修改`：
<img width="1183" alt="screen shot 2017-06-09 at 11 57 11 am" src="https://user-images.githubusercontent.com/2911620/26960559-db0d7eee-4d0a-11e7-9665-c5af8fd1aebe.png">

**Comment by lorriexingfang** [comment]
原来在这里……配了一下，现在点Implicit OAuth有输出了。但是点OAuth和OAuth without new code还是不行。

**Comment by JasonBoy** [comment]
提示什么错误？

**Comment by lorriexingfang** [comment]
哦，可以了。之前自己加了点代码。屏蔽掉就好了。非常非常感谢！可以close了。

**Comment by JasonBoy** [comment]
👌
